version: '3.8'

services:
  web:
    image: php:8.0-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

  volumes:
    mysql_data:
